"""add_coupons

Revision ID: 0b10c51db7ab
Revises: 55c708bd21a5
Create Date: 2026-06-05 17:52:34.023822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b10c51db7ab'
down_revision: Union[str, Sequence[str], None] = '55c708bd21a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_usages_coupon_id'), 'coupon_usages', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_created_at'), 'coupon_usages', ['created_at'], unique=False)
    op.create_index(op.f('ix_coupon_usages_order_id'), 'coupon_usages', ['order_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_tenant_id'), 'coupon_usages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_user_id'), 'coupon_usages', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_coupon_usages_coupon_id'), table_name='user_coupon_usages')
    op.drop_index(op.f('ix_user_coupon_usages_tenant_id'), table_name='user_coupon_usages')
    op.drop_index(op.f('ix_user_coupon_usages_user_id'), table_name='user_coupon_usages')
    op.drop_table('user_coupon_usages')
    op.drop_table('coupon_categories')
    op.drop_table('coupon_products')
    op.add_column('coupons', sa.Column('min_order_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('coupons', sa.Column('usage_limit_total', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('usage_limit_per_user', sa.Integer(), nullable=False))
    op.add_column('coupons', sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=False)
    op.drop_column('coupons', 'min_cart_value')
    op.drop_column('coupons', 'apply_to')
    op.drop_column('coupons', 'user_limit')
    op.drop_column('coupons', 'usage_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('usage_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coupons', sa.Column('user_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('coupons', sa.Column('apply_to', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('coupons', sa.Column('min_cart_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_column('coupons', 'rules')
    op.drop_column('coupons', 'usage_limit_per_user')
    op.drop_column('coupons', 'usage_limit_total')
    op.drop_column('coupons', 'min_order_value')
    op.create_table('coupon_products',
    sa.Column('coupon_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('coupon_products_coupon_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('coupon_products_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', 'product_id', name=op.f('coupon_products_pkey'))
    )
    op.create_table('coupon_categories',
    sa.Column('coupon_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('coupon_categories_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('coupon_categories_coupon_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', 'category_id', name=op.f('coupon_categories_pkey'))
    )
    op.create_table('user_coupon_usages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('coupon_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('user_coupon_usages_coupon_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('user_coupon_usages_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_coupon_usages_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_coupon_usages_pkey')),
    sa.UniqueConstraint('user_id', 'coupon_id', name=op.f('uq_user_coupon_usage'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_coupon_usages_user_id'), 'user_coupon_usages', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_coupon_usages_tenant_id'), 'user_coupon_usages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_coupon_usages_coupon_id'), 'user_coupon_usages', ['coupon_id'], unique=False)
    op.drop_index(op.f('ix_coupon_usages_user_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_tenant_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_order_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_created_at'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_coupon_id'), table_name='coupon_usages')
    op.drop_table('coupon_usages')
    # ### end Alembic commands ###
