"""add tenant settings columns

Revision ID: 0b19e4a8ad85
Revises: 79ee244165ac
Create Date: 2026-08-03 16:00:40.144916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b19e4a8ad85'
down_revision: Union[str, Sequence[str], None] = '79ee244165ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('contact_telephone', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('whatsapp_number', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('support_email', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('gstin_code', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('currency', sa.String(), server_default='INR', nullable=False))
    op.add_column('tenants', sa.Column('payment_public_key', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('payment_secret_key', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('payment_sandbox_mode', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'payment_sandbox_mode')
    op.drop_column('tenants', 'payment_secret_key')
    op.drop_column('tenants', 'payment_public_key')
    op.drop_column('tenants', 'currency')
    op.drop_column('tenants', 'gstin_code')
    op.drop_column('tenants', 'support_email')
    op.drop_column('tenants', 'whatsapp_number')
    op.drop_column('tenants', 'contact_telephone')
    # ### end Alembic commands ###
