"""add_product_pricing_rules

Revision ID: 1f7791f74e7e
Revises: a8037e509fa1
Create Date: 2026-06-06 16:23:41.123584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7791f74e7e'
down_revision: Union[str, Sequence[str], None] = 'a8037e509fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_hour', sa.Integer(), nullable=True),
    sa.Column('end_hour', sa.Integer(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('max_stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_pricing_rules_location_id'), 'product_pricing_rules', ['location_id'], unique=False)
    op.create_index(op.f('ix_product_pricing_rules_pincode'), 'product_pricing_rules', ['pincode'], unique=False)
    op.create_index(op.f('ix_product_pricing_rules_product_id'), 'product_pricing_rules', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_pricing_rules_tenant_id'), 'product_pricing_rules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_pricing_rules_tenant_id'), table_name='product_pricing_rules')
    op.drop_index(op.f('ix_product_pricing_rules_product_id'), table_name='product_pricing_rules')
    op.drop_index(op.f('ix_product_pricing_rules_pincode'), table_name='product_pricing_rules')
    op.drop_index(op.f('ix_product_pricing_rules_location_id'), table_name='product_pricing_rules')
    op.drop_table('product_pricing_rules')
    # ### end Alembic commands ###
