"""add_tenant_branding_fields

Revision ID: 31f2118230a1
Revises: ae6245484d90
Create Date: 2026-07-20 13:05:29.507555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f2118230a1'
down_revision: Union[str, Sequence[str], None] = 'ae6245484d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('favicon_url', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('primary_color', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('secondary_color', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('theme_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'theme_name')
    op.drop_column('tenants', 'secondary_color')
    op.drop_column('tenants', 'primary_color')
    op.drop_column('tenants', 'favicon_url')
    op.drop_column('tenants', 'logo_url')
    # ### end Alembic commands ###
