"""add_user_addresses

Revision ID: 4243d95cbf34
Revises: 4c2cc02f07a5
Create Date: 2026-06-05 13:46:51.906510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4243d95cbf34'
down_revision: Union[str, Sequence[str], None] = '4c2cc02f07a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('addressline1', sa.String(), nullable=False),
    sa.Column('addressline2', sa.String(), nullable=True),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('cusomername', sa.String(), nullable=False),
    sa.Column('phonenumber', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('lat_long', sa.String(), nullable=True),
    sa.Column('3rd_party_app_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_addresses')
    # ### end Alembic commands ###
