"""add_product_pricing

Revision ID: 4dfeb849c6b8
Revises: bd8c908b9ee9
Create Date: 2026-06-05 15:59:48.561210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfeb849c6b8'
down_revision: Union[str, Sequence[str], None] = 'bd8c908b9ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'type', name='uq_tenant_pricing_type')
    )
    op.create_index(op.f('ix_pricing_types_tenant_id'), 'pricing_types', ['tenant_id'], unique=False)
    op.create_table('product_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('pricing_type_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pricing_type_id'], ['pricing_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'pricing_type_id', name='uq_product_pricing_type_price')
    )
    op.create_index(op.f('ix_product_prices_pricing_type_id'), 'product_prices', ['pricing_type_id'], unique=False)
    op.create_index(op.f('ix_product_prices_product_id'), 'product_prices', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_prices_product_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_pricing_type_id'), table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index(op.f('ix_pricing_types_tenant_id'), table_name='pricing_types')
    op.drop_table('pricing_types')
    # ### end Alembic commands ###
