"""add_coupons

Revision ID: 55c708bd21a5
Revises: 5053e6a7f9b4
Create Date: 2026-06-05 17:48:13.771660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c708bd21a5'
down_revision: Union[str, Sequence[str], None] = '5053e6a7f9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('discount_type', sa.String(), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_cart_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('user_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('apply_to', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_tenant_coupon_code')
    )
    op.create_index(op.f('ix_coupons_tenant_id'), 'coupons', ['tenant_id'], unique=False)
    op.create_table('coupon_categories',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', 'category_id')
    )
    op.create_table('coupon_products',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', 'product_id')
    )
    op.create_table('user_coupon_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'coupon_id', name='uq_user_coupon_usage')
    )
    op.create_index(op.f('ix_user_coupon_usages_coupon_id'), 'user_coupon_usages', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_user_coupon_usages_tenant_id'), 'user_coupon_usages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_coupon_usages_user_id'), 'user_coupon_usages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_coupon_usages_user_id'), table_name='user_coupon_usages')
    op.drop_index(op.f('ix_user_coupon_usages_tenant_id'), table_name='user_coupon_usages')
    op.drop_index(op.f('ix_user_coupon_usages_coupon_id'), table_name='user_coupon_usages')
    op.drop_table('user_coupon_usages')
    op.drop_table('coupon_products')
    op.drop_table('coupon_categories')
    op.drop_index(op.f('ix_coupons_tenant_id'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
