"""add pending cart payments table

Revision ID: 5b5acce85f20
Revises: e975c2718823
Create Date: 2026-06-06 17:18:33.519128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b5acce85f20'
down_revision: Union[str, Sequence[str], None] = 'e975c2718823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_cart_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gateway_order_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cart_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('billing_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('gateway', sa.String(), nullable=False),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_cart_payments_gateway_order_id'), 'pending_cart_payments', ['gateway_order_id'], unique=True)
    op.create_index(op.f('ix_pending_cart_payments_status'), 'pending_cart_payments', ['status'], unique=False)
    op.create_index(op.f('ix_pending_cart_payments_tenant_id'), 'pending_cart_payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pending_cart_payments_user_id'), 'pending_cart_payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_cart_payments_user_id'), table_name='pending_cart_payments')
    op.drop_index(op.f('ix_pending_cart_payments_tenant_id'), table_name='pending_cart_payments')
    op.drop_index(op.f('ix_pending_cart_payments_status'), table_name='pending_cart_payments')
    op.drop_index(op.f('ix_pending_cart_payments_gateway_order_id'), table_name='pending_cart_payments')
    op.drop_table('pending_cart_payments')
    # ### end Alembic commands ###
