"""add_product_shipping

Revision ID: 74d4e8f91ce3
Revises: 0b19e4a8ad85
Create Date: 2026-08-13 17:14:58.491891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d4e8f91ce3'
down_revision: Union[str, Sequence[str], None] = '0b19e4a8ad85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
