"""update_tenant_cart_coupons_deliveries

Revision ID: 757a4bdaa814
Revises: 0b10c51db7ab
Create Date: 2026-06-05 18:09:53.459626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '757a4bdaa814'
down_revision: Union[str, Sequence[str], None] = '0b10c51db7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('allow_multiple_coupons', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_carts', sa.Column('applied_coupons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('user_carts', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('user_carts', sa.Column('delivery_service', sa.String(), nullable=True))
    op.add_column('user_carts', sa.Column('estimated_days', sa.Integer(), nullable=True))
    op.add_column('user_carts', sa.Column('delivery_address_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user_carts', 'user_addresses', ['delivery_address_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_carts', type_='foreignkey')
    op.drop_column('user_carts', 'delivery_address_id')
    op.drop_column('user_carts', 'estimated_days')
    op.drop_column('user_carts', 'delivery_service')
    op.drop_column('user_carts', 'delivery_fee')
    op.drop_column('user_carts', 'applied_coupons')
    op.drop_column('tenants', 'allow_multiple_coupons')
    # ### end Alembic commands ###
