"""Add Shiprocket fields to Tenant

Revision ID: 79ee244165ac
Revises: 31f2118230a1
Create Date: 2026-08-03 14:57:15.557792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79ee244165ac'
down_revision: Union[str, Sequence[str], None] = '31f2118230a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('shiprocket_email', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('shiprocket_password', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('shiprocket_token', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('shiprocket_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'shiprocket_token_expires')
    op.drop_column('tenants', 'shiprocket_token')
    op.drop_column('tenants', 'shiprocket_password')
    op.drop_column('tenants', 'shiprocket_email')
    # ### end Alembic commands ###
