"""add_product_attributes

Revision ID: 7a51fcf94a4b
Revises: e3aafb2544b2
Create Date: 2026-06-06 14:45:37.015344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a51fcf94a4b'
down_revision: Union[str, Sequence[str], None] = 'e3aafb2544b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_attribute_name')
    )
    op.create_index(op.f('ix_attributes_tenant_id'), 'attributes', ['tenant_id'], unique=False)
    op.create_table('product_attribute_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'attribute_id', name='uq_product_attribute_value')
    )
    op.create_index(op.f('ix_product_attribute_values_attribute_id'), 'product_attribute_values', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_product_attribute_values_product_id'), 'product_attribute_values', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_attribute_values_product_id'), table_name='product_attribute_values')
    op.drop_index(op.f('ix_product_attribute_values_attribute_id'), table_name='product_attribute_values')
    op.drop_table('product_attribute_values')
    op.drop_index(op.f('ix_attributes_tenant_id'), table_name='attributes')
    op.drop_table('attributes')
    # ### end Alembic commands ###
