"""create_payment_gateway_configs

Revision ID: 81c541defadb
Revises: a740b3999f64
Create Date: 2026-06-06 16:57:52.809563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81c541defadb'
down_revision: Union[str, Sequence[str], None] = 'a740b3999f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_gateway_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'gateway', name='uq_tenant_gateway_config')
    )
    op.create_index(op.f('ix_payment_gateway_configs_tenant_id'), 'payment_gateway_configs', ['tenant_id'], unique=False)
    op.add_column('order_payments', sa.Column('gateway', sa.String(), nullable=True))
    op.create_index(op.f('ix_order_payments_gateway'), 'order_payments', ['gateway'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_payments_gateway'), table_name='order_payments')
    op.drop_column('order_payments', 'gateway')
    op.drop_index(op.f('ix_payment_gateway_configs_tenant_id'), table_name='payment_gateway_configs')
    op.drop_table('payment_gateway_configs')
    # ### end Alembic commands ###
