"""add_product_grouping

Revision ID: 89a403173b05
Revises: c60d82fc77fc
Create Date: 2026-06-06 15:14:59.697005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a403173b05'
down_revision: Union[str, Sequence[str], None] = 'c60d82fc77fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_product_group_name')
    )
    op.create_index(op.f('ix_product_groups_tenant_id'), 'product_groups', ['tenant_id'], unique=False)
    op.create_table('product_group_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['product_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'group_id', name='uq_product_group_link')
    )
    op.create_index(op.f('ix_product_group_links_group_id'), 'product_group_links', ['group_id'], unique=False)
    op.create_index(op.f('ix_product_group_links_product_id'), 'product_group_links', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_group_links_product_id'), table_name='product_group_links')
    op.drop_index(op.f('ix_product_group_links_group_id'), table_name='product_group_links')
    op.drop_table('product_group_links')
    op.drop_index(op.f('ix_product_groups_tenant_id'), table_name='product_groups')
    op.drop_table('product_groups')
    # ### end Alembic commands ###
