"""add_user_addresses

Revision ID: 921ed015cd90
Revises: 4243d95cbf34
Create Date: 2026-06-05 13:48:56.938727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921ed015cd90'
down_revision: Union[str, Sequence[str], None] = '4243d95cbf34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_addresses', sa.Column('address_line_1', sa.String(), nullable=False))
    op.add_column('user_addresses', sa.Column('address_line_2', sa.String(), nullable=True))
    op.add_column('user_addresses', sa.Column('customer_name', sa.String(), nullable=False))
    op.add_column('user_addresses', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('user_addresses', sa.Column('third_party_app_address', sa.String(), nullable=True))
    op.drop_column('user_addresses', 'phonenumber')
    op.drop_column('user_addresses', 'addressline1')
    op.drop_column('user_addresses', 'cusomername')
    op.drop_column('user_addresses', '3rd_party_app_address')
    op.drop_column('user_addresses', 'addressline2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_addresses', sa.Column('addressline2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_addresses', sa.Column('3rd_party_app_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_addresses', sa.Column('cusomername', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_addresses', sa.Column('addressline1', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_addresses', sa.Column('phonenumber', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_addresses', 'third_party_app_address')
    op.drop_column('user_addresses', 'phone_number')
    op.drop_column('user_addresses', 'customer_name')
    op.drop_column('user_addresses', 'address_line_2')
    op.drop_column('user_addresses', 'address_line_1')
    # ### end Alembic commands ###
