"""add_stock_wallet_referral_reviews

Revision ID: 92d5bb78e15c
Revises: 89a403173b05
Create Date: 2026-06-06 15:29:18.105725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d5bb78e15c'
down_revision: Union[str, Sequence[str], None] = '89a403173b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id'),
    sa.UniqueConstraint('tenant_id', 'product_id', name='uq_tenant_product_stock')
    )
    op.create_index(op.f('ix_product_stocks_tenant_id'), 'product_stocks', ['tenant_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('rating_points', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_entity_id'), 'reviews', ['entity_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('user_referral_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referral_user_id', sa.UUID(), nullable=False),
    sa.Column('referrer_user_id', sa.UUID(), nullable=False),
    sa.Column('referred_entity', sa.String(), nullable=False),
    sa.Column('referred_entity_id', sa.UUID(), nullable=True),
    sa.Column('points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referral_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_referral_histories_referral_user_id'), 'user_referral_histories', ['referral_user_id'], unique=False)
    op.create_index(op.f('ix_user_referral_histories_referrer_user_id'), 'user_referral_histories', ['referrer_user_id'], unique=False)
    op.create_table('user_referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('referral_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_referral_points_transaction_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_referral_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_referral_id'], ['user_referrals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['user_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_referral_points_transaction_histories_user_referral_id'), 'user_referral_points_transaction_histories', ['user_referral_id'], unique=False)
    op.create_index(op.f('ix_user_referral_points_transaction_histories_wallet_id'), 'user_referral_points_transaction_histories', ['wallet_id'], unique=False)
    op.create_table('user_wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['user_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_wallet_transactions_user_id'), 'user_wallet_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_wallet_transactions_wallet_id'), 'user_wallet_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_wallet_transactions_wallet_id'), table_name='user_wallet_transactions')
    op.drop_index(op.f('ix_user_wallet_transactions_user_id'), table_name='user_wallet_transactions')
    op.drop_table('user_wallet_transactions')
    op.drop_index(op.f('ix_user_referral_points_transaction_histories_wallet_id'), table_name='user_referral_points_transaction_histories')
    op.drop_index(op.f('ix_user_referral_points_transaction_histories_user_referral_id'), table_name='user_referral_points_transaction_histories')
    op.drop_table('user_referral_points_transaction_histories')
    op.drop_table('user_wallets')
    op.drop_table('user_referrals')
    op.drop_index(op.f('ix_user_referral_histories_referrer_user_id'), table_name='user_referral_histories')
    op.drop_index(op.f('ix_user_referral_histories_referral_user_id'), table_name='user_referral_histories')
    op.drop_table('user_referral_histories')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_entity_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_product_stocks_tenant_id'), table_name='product_stocks')
    op.drop_table('product_stocks')
    # ### end Alembic commands ###
