"""add_pricing_type_to_rules_and_attributes

Revision ID: a740b3999f64
Revises: 1f7791f74e7e
Create Date: 2026-06-06 16:43:00.131123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a740b3999f64'
down_revision: Union[str, Sequence[str], None] = '1f7791f74e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_attribute_values', sa.Column('pricing_type_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_product_attribute_values_pricing_type_id'), 'product_attribute_values', ['pricing_type_id'], unique=False)
    op.create_foreign_key(None, 'product_attribute_values', 'pricing_types', ['pricing_type_id'], ['id'], ondelete='SET NULL')
    op.add_column('product_pricing_rules', sa.Column('pricing_type_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_product_pricing_rules_pricing_type_id'), 'product_pricing_rules', ['pricing_type_id'], unique=False)
    op.create_foreign_key(None, 'product_pricing_rules', 'pricing_types', ['pricing_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_pricing_rules', type_='foreignkey')
    op.drop_index(op.f('ix_product_pricing_rules_pricing_type_id'), table_name='product_pricing_rules')
    op.drop_column('product_pricing_rules', 'pricing_type_id')
    op.drop_constraint(None, 'product_attribute_values', type_='foreignkey')
    op.drop_index(op.f('ix_product_attribute_values_pricing_type_id'), table_name='product_attribute_values')
    op.drop_column('product_attribute_values', 'pricing_type_id')
    # ### end Alembic commands ###
