"""sync_db_with_models

Revision ID: ae6245484d90
Revises: f1a2b3c4d5e6
Create Date: 2026-07-20 12:11:12.403323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae6245484d90'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_tenant_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_razorpay_payment_id'), table_name='orders')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'razorpay_payment_id')
    op.drop_column('orders', 'razorpay_order_id')
    op.drop_column('products', 'classifications')
    op.drop_column('tenant_domains', 'is_verified')
    op.drop_column('tenant_domains', 'is_active')
    # 1. Add column as nullable
    op.add_column('tenants', sa.Column('business_name', sa.String(), nullable=True))
    
    # 2. Populate existing rows with a default value
    op.execute("UPDATE tenants SET business_name = 'Tenant ' || id::text WHERE business_name IS NULL")
    
    # 3. Alter column to be NOT NULL
    op.alter_column('tenants', 'business_name', nullable=False)
    
    op.add_column('tenants', sa.Column('allow_multiple_coupons', sa.Boolean(), nullable=True))
    op.execute("UPDATE tenants SET allow_multiple_coupons = false WHERE allow_multiple_coupons IS NULL")
    op.alter_column('tenants', 'allow_multiple_coupons', nullable=False)
    op.drop_index(op.f('ix_tenants_store_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_subdomain'), table_name='tenants')
    op.create_index(op.f('ix_tenants_business_name'), 'tenants', ['business_name'], unique=True)
    op.drop_column('tenants', 'store_name')
    op.drop_column('tenants', 'subdomain')
    op.drop_column('tenants', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('subdomain', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('store_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tenants_business_name'), table_name='tenants')
    op.create_index(op.f('ix_tenants_subdomain'), 'tenants', ['subdomain'], unique=True)
    op.create_index(op.f('ix_tenants_store_name'), 'tenants', ['store_name'], unique=True)
    op.drop_column('tenants', 'allow_multiple_coupons')
    op.drop_column('tenants', 'business_name')
    op.add_column('tenant_domains', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('tenant_domains', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('classifications', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('razorpay_order_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('razorpay_payment_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_orders_razorpay_payment_id'), 'orders', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), server_default=sa.text("'RAZORPAY'::character varying"), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('webhook_events_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_events_pkey')),
    sa.UniqueConstraint('event_id', 'provider', name=op.f('uq_webhook_event_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_webhook_events_tenant_id'), 'webhook_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=False)
    # ### end Alembic commands ###
