"""add_product_attributes

Revision ID: c60d82fc77fc
Revises: 7a51fcf94a4b
Create Date: 2026-06-06 14:49:04.793982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c60d82fc77fc'
down_revision: Union[str, Sequence[str], None] = '7a51fcf94a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('hex_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_id', 'value', name='uq_attribute_value')
    )
    op.create_index(op.f('ix_attribute_values_attribute_id'), 'attribute_values', ['attribute_id'], unique=False)
    op.add_column('attributes', sa.Column('display_name', sa.String(), nullable=False))
    op.drop_column('attributes', 'updated_at')
    op.add_column('product_attribute_values', sa.Column('attribute_value_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_product_attribute_values_attribute_id'), table_name='product_attribute_values')
    op.drop_constraint(op.f('uq_product_attribute_value'), 'product_attribute_values', type_='unique')
    op.create_index(op.f('ix_product_attribute_values_attribute_value_id'), 'product_attribute_values', ['attribute_value_id'], unique=False)
    op.create_unique_constraint('uq_product_attribute_value_link', 'product_attribute_values', ['product_id', 'attribute_value_id'])
    op.drop_constraint(op.f('product_attribute_values_attribute_id_fkey'), 'product_attribute_values', type_='foreignkey')
    op.create_foreign_key(None, 'product_attribute_values', 'attribute_values', ['attribute_value_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product_attribute_values', 'attribute_id')
    op.drop_column('product_attribute_values', 'value')
    op.drop_column('product_attribute_values', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_attribute_values', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('product_attribute_values', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('product_attribute_values', sa.Column('attribute_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_attribute_values', type_='foreignkey')
    op.create_foreign_key(op.f('product_attribute_values_attribute_id_fkey'), 'product_attribute_values', 'attributes', ['attribute_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_product_attribute_value_link', 'product_attribute_values', type_='unique')
    op.drop_index(op.f('ix_product_attribute_values_attribute_value_id'), table_name='product_attribute_values')
    op.create_unique_constraint(op.f('uq_product_attribute_value'), 'product_attribute_values', ['product_id', 'attribute_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_product_attribute_values_attribute_id'), 'product_attribute_values', ['attribute_id'], unique=False)
    op.drop_column('product_attribute_values', 'attribute_value_id')
    op.add_column('attributes', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('attributes', 'display_name')
    op.drop_index(op.f('ix_attribute_values_attribute_id'), table_name='attribute_values')
    op.drop_table('attribute_values')
    # ### end Alembic commands ###
