"""add_media_table

Revision ID: df79fa814103
Revises: 4dfeb849c6b8
Create Date: 2026-06-05 16:28:22.730305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df79fa814103'
down_revision: Union[str, Sequence[str], None] = '4dfeb849c6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('file_extension', sa.String(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('meta_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_entity_id'), 'media', ['entity_id'], unique=False)
    op.create_index(op.f('ix_media_entity_name'), 'media', ['entity_name'], unique=False)
    op.create_index(op.f('ix_media_tenant_id'), 'media', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_tenant_id'), table_name='media')
    op.drop_index(op.f('ix_media_entity_name'), table_name='media')
    op.drop_index(op.f('ix_media_entity_id'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
