"""add_orders_payments_returns

Revision ID: e3aafb2544b2
Revises: 757a4bdaa814
Create Date: 2026-06-05 18:25:16.903010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3aafb2544b2'
down_revision: Union[str, Sequence[str], None] = '757a4bdaa814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('delivery_address_id', sa.UUID(), nullable=True),
    sa.Column('delivery_service', sa.String(), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.Column('item_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('applied_coupons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shipping_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['user_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('order_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('transaction_reference', sa.String(), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_payments_order_id'), 'order_payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_payments_status'), 'order_payments', ['status'], unique=False)
    op.create_index(op.f('ix_order_payments_tenant_id'), 'order_payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_order_payments_transaction_reference'), 'order_payments', ['transaction_reference'], unique=False)
    op.create_table('order_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('refund_status', sa.String(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_returns_order_id'), 'order_returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_returns_refund_status'), 'order_returns', ['refund_status'], unique=False)
    op.create_index(op.f('ix_order_returns_status'), 'order_returns', ['status'], unique=False)
    op.create_index(op.f('ix_order_returns_tenant_id'), 'order_returns', ['tenant_id'], unique=False)
    op.create_table('order_return_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_return_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_return_id'], ['order_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_return_items_order_item_id'), 'order_return_items', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_order_return_items_order_return_id'), 'order_return_items', ['order_return_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_return_items_order_return_id'), table_name='order_return_items')
    op.drop_index(op.f('ix_order_return_items_order_item_id'), table_name='order_return_items')
    op.drop_table('order_return_items')
    op.drop_index(op.f('ix_order_returns_tenant_id'), table_name='order_returns')
    op.drop_index(op.f('ix_order_returns_status'), table_name='order_returns')
    op.drop_index(op.f('ix_order_returns_refund_status'), table_name='order_returns')
    op.drop_index(op.f('ix_order_returns_order_id'), table_name='order_returns')
    op.drop_table('order_returns')
    op.drop_index(op.f('ix_order_payments_transaction_reference'), table_name='order_payments')
    op.drop_index(op.f('ix_order_payments_tenant_id'), table_name='order_payments')
    op.drop_index(op.f('ix_order_payments_status'), table_name='order_payments')
    op.drop_index(op.f('ix_order_payments_order_id'), table_name='order_payments')
    op.drop_table('order_payments')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
