"""create_tenant_payment_gateways

Revision ID: e975c2718823
Revises: 81c541defadb
Create Date: 2026-06-06 17:06:12.448235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e975c2718823'
down_revision: Union[str, Sequence[str], None] = '81c541defadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_gateways',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenant_commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('linked_account_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_commissions_tenant_id'), 'tenant_commissions', ['tenant_id'], unique=True)
    op.create_table('tenant_payment_gateways',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('gateway_id', sa.UUID(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['payment_gateways.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'gateway_id', name='uq_tenant_gateway')
    )
    op.create_index(op.f('ix_tenant_payment_gateways_gateway_id'), 'tenant_payment_gateways', ['gateway_id'], unique=False)
    op.create_index(op.f('ix_tenant_payment_gateways_tenant_id'), 'tenant_payment_gateways', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_payment_gateway_configs_tenant_id'), table_name='payment_gateway_configs')
    op.drop_table('payment_gateway_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_gateway_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('gateway', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('webhook_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('payment_gateway_configs_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_gateway_configs_pkey')),
    sa.UniqueConstraint('tenant_id', 'gateway', name=op.f('uq_tenant_gateway_config'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_payment_gateway_configs_tenant_id'), 'payment_gateway_configs', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_tenant_payment_gateways_tenant_id'), table_name='tenant_payment_gateways')
    op.drop_index(op.f('ix_tenant_payment_gateways_gateway_id'), table_name='tenant_payment_gateways')
    op.drop_table('tenant_payment_gateways')
    op.drop_index(op.f('ix_tenant_commissions_tenant_id'), table_name='tenant_commissions')
    op.drop_table('tenant_commissions')
    op.drop_table('payment_gateways')
    # ### end Alembic commands ###
